### PR TITLE
RDNN appdata and .desktop

### PR DESCRIPTION
**Pull request by cassidyjames**
This is best practice, but also required for AppCenter.

### CODE REVIEW

**Comment by stuartlangridge** [comment]
OK. I'm not hugely happy about this, since reverse-domain-naming is convenient for big-system organisation but stupid for actual users -- if I'm poking around my filesystem trying to find the desktop file for Pick so that I can make changes to it, I should be looking for `pick.desktop`, not `biz.nowhere.whatever.irrelevant.pick.desktop`. But, fine, OK. However, it should be `org.kryogenix.pick` etc, not `com.github.stuartlangridge` which is not my domain and not under my control. Does AppCenter _require_ that I make the ID name github? Or does it have to just be something reverse-domain and unique to my app and me?

**Comment by cassidyjames** [comment]
The RDNN for .desktop files is not something elementary invented; it's in the [FreeDesktop.Org desktop entry spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html), is being adopted by GNOME, and is required for some modern DE features. 

I believe right now AppCenter does just expect a `com.github` RDNN; theoretically in a future where we supported GitLab repos as well, it'd expect the RDNN of the GitLab repo.

**Comment by stuartlangridge** [comment]
Yeah, I wasn't blaming elementary for the rdnn, I just don't like it ;-)

However, I like a lot, lot less that I have to define the ID for my app as being a github URL. That means that if I ever move, it's suddenly a new app. Is there some reason why it's an actual requirement that I have to hardcode the name of github into the unique unchanging ID for an app I wrote?

**Comment by cassidyjames** [comment]
Yes, because AppCenter has a 1:1 association of a repo to an app. If the code lives on GitHub, the app is hosted on GitHub. Feel free to [file an issue](https://github.com/elementary/houston) for self-defined RDNN, but that's the way AppCenter works, at least right now.

**Comment by stuartlangridge** [comment]
Good call. https://github.com/elementary/houston/issues/436 filed.

**Pull request closed without merging**
